name = "hono-be"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# D1 Database Binding
# IMPORTANT: You must replace "your-database-id" with your actual D1 database ID.
# You can create a D1 database and get its ID by running:
# npx wrangler d1 create <database_name>
[[d1_databases]]
binding = "DB" # This binding will be available in your worker code (e.g., c.env.DB)
database_name = "hono_db"
database_id = "${D1_DATABASE_ID}" # <-- REPLACE THIS
migrations_dir = "drizzle"
